version: '3.5'

services:
  db:
    image: postgres:14.1-alpine3.15
    restart: always
    container_name: hello-todo-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: niklist
