version: '3.5'

services:
  db:
    image: postgres:14.1-alpine3.15
    container_name: hello-todo-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: niklist
